/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 CKEditor 4 LTS ("Long Term Support") is available under the terms of the Extended Support Model.
*/
(function(){function D(b){function d(){for(var a=f(),e=CKEDITOR.tools.clone(b.config.toolbarGroups)||v(b),n=0;n<e.length;n++){var g=e[n];if("/"!=g){"string"==typeof g&&(g=e[n]={name:g});var l,d=g.groups;if(d)for(var h=0;h<d.length;h++)l=d[h],(l=a[l])&&c(g,l);(l=a[g.name])&&c(g,l)}}return e}function f(){var a={},c,e,g;for(c in b.ui.items)e=b.ui.items[c],g=e.toolbar||"others",g=g.split(","),e=g[0],g=parseInt(g[1]||-1,10),a[e]||(a[e]=[]),a[e].push({name:c,order:g});for(e in a)a[e]=a[e].sort(function(a,
b){return a.order==b.order?0:0>b.order?-1:0>a.order?1:a.order<b.order?-1:1});return a}function c(c,e){if(e.length){c.items?c.items.push(b.ui.create("-")):c.items=[];for(var d;d=e.shift();)d="string"==typeof d?d:d.name,a&&-1!=CKEDITOR.tools.indexOf(a,d)||(d=b.ui.create(d))&&b.addFeature(d)&&c.items.push(d)}}function h(a){var b=[],e,d,h;for(e=0;e<a.length;++e)d=a[e],h={},"/"==d?b.push(d):CKEDITOR.tools.isArray(d)?(c(h,CKEDITOR.tools.clone(d)),b.push(h)):d.items&&(c(h,CKEDITOR.tools.clone(d.items)),
h.name=d.name,b.push(h));return b}var a=function(a){return a&&"string"===typeof a?a.split(","):a}(b.config.removeButtons),e=b.config.toolbar;"string"==typeof e&&(e=b.config["toolbar_"+e]);return b.toolbar=e?h(e):d()}function v(b){return b._.toolbarGroups||(b._.toolbarGroups=[{name:"document",groups:["mode","document","doctools"]},{name:"clipboard",groups:["clipboard","undo"]},{name:"editing",groups:["find","selection","spellchecker"]},{name:"forms"},"/",{name:"basicstyles",groups:["basicstyles","cleanup"]},
{name:"paragraph",groups:["list","indent","blocks","align","bidi"]},{name:"links"},{name:"insert"},"/",{name:"styles"},{name:"colors"},{name:"tools"},{name:"others"},{name:"about"}])}var z=function(){this.toolbars=[]};z.prototype.focus=function(){for(var b=0,d;d=this.toolbars[b++];)for(var f=0,c;c=d.items[f++];)if(c.focus){c.focus();return}};var E={modes:{wysiwyg:1,source:1},readOnly:1,exec:function(b){b.toolbox&&(CKEDITOR.env.ie||CKEDITOR.env.air?setTimeout(function(){b.toolbox.focus()},100):b.toolbox.focus())}};
CKEDITOR.plugins.add("toolbar",{requires:"button",lang:"af,ar,az,bg,bn,bs,ca,cs,cy,da,de,de-ch,el,en,en-au,en-ca,en-gb,eo,es,es-mx,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,oc,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn",init:function(b){var d,f=function(c,h){var a,e="rtl"==b.lang.dir,k=b.config.toolbarGroupCycling,q=e?37:39,e=e?39:37,k=void 0===k||k;switch(h){case 9:case CKEDITOR.SHIFT+9:for(;!a||!a.items.length;)if(a=9==
h?(a?a.next:c.toolbar.next)||b.toolbox.toolbars[0]:(a?a.previous:c.toolbar.previous)||b.toolbox.toolbars[b.toolbox.toolbars.length-1],a.items.length)for(c=a.items[d?a.items.length-1:0];c&&!c.focus;)(c=d?c.previous:c.next)||(a=0);c&&c.focus();return!1;case q:a=c;do a=a.next,!a&&k&&(a=c.toolbar.items[0]);while(a&&!a.focus);a?a.focus():f(c,9);return!1;case 40:return c.button&&c.button.hasArrow?c.execute():f(c,40==h?q:e),!1;case e:case 38:a=c;do a=a.previous,!a&&k&&(a=c.toolbar.items[c.toolbar.items.length-
1]);while(a&&!a.focus);a?a.focus():(d=1,f(c,CKEDITOR.SHIFT+9),d=0);return!1;case 27:return b.focus(),!1;case 13:case 32:return c.execute(),!1;case CKEDITOR.ALT+122:return b.execCommand("elementsPathFocus"),!1}return!0};b.on("uiSpace",function(c){if(c.data.space==b.config.toolbarLocation){c.removeListener();b.toolbox=new z;var d=CKEDITOR.tools.getNextId(),a=['\x3cspan id\x3d"',d,'" class\x3d"cke_voice_label"\x3e',b.lang.toolbar.toolbars,"\x3c/span\x3e",'\x3cspan id\x3d"'+b.ui.spaceId("toolbox")+'" class\x3d"cke_toolbox" role\x3d"group" aria-labelledby\x3d"',
d,'" onmousedown\x3d"return false;"\x3e'],d=!1!==b.config.toolbarStartupExpanded,e,k;b.config.toolbarCanCollapse&&b.elementMode!=CKEDITOR.ELEMENT_MODE_INLINE&&a.push('\x3cspan class\x3d"cke_toolbox_main"'+(d?"\x3e":' style\x3d"display:none"\x3e'));for(var q=b.toolbox.toolbars,n=D(b),g=n.length,l=0;l<g;l++){var r,m=0,w,p=n[l],v="/"!==p&&("/"===n[l+1]||l==g-1),x;if(p)if(e&&(a.push("\x3c/span\x3e"),k=e=0),"/"===p)a.push('\x3cspan class\x3d"cke_toolbar_break"\x3e\x3c/span\x3e');else{x=p.items||p;for(var y=
0;y<x.length;y++){var t=x[y],A;if(t){var B=function(c){c=c.render(b,a);u=m.items.push(c)-1;0<u&&(c.previous=m.items[u-1],c.previous.next=c);c.toolbar=m;c.onkey=f};if(t.type==CKEDITOR.UI_SEPARATOR)k=e&&t;else{A=!1!==t.canGroup;if(!m){r=CKEDITOR.tools.getNextId();m={id:r,items:[]};w=p.name&&(b.lang.toolbar.toolbarGroups[p.name]||p.name);a.push('\x3cspan id\x3d"',r,'" class\x3d"cke_toolbar'+(v?' cke_toolbar_last"':'"'),w?' aria-labelledby\x3d"'+r+'_label"':"",' role\x3d"toolbar"\x3e');w&&a.push('\x3cspan id\x3d"',
r,'_label" class\x3d"cke_voice_label"\x3e',w,"\x3c/span\x3e");a.push('\x3cspan class\x3d"cke_toolbar_start"\x3e\x3c/span\x3e');var u=q.push(m)-1;0<u&&(m.previous=q[u-1],m.previous.next=m)}A?e||(a.push('\x3cspan class\x3d"cke_toolgroup" role\x3d"presentation"\x3e'),e=1):e&&(a.push("\x3c/span\x3e"),e=0);k&&(B(k),k=0);B(t)}}}e&&(a.push("\x3c/span\x3e"),k=e=0);m&&a.push('\x3cspan class\x3d"cke_toolbar_end"\x3e\x3c/span\x3e\x3c/span\x3e')}}b.config.toolbarCanCollapse&&a.push("\x3c/span\x3e");if(b.config.toolbarCanCollapse&&
b.elementMode!=CKEDITOR.ELEMENT_MODE_INLINE){var C=CKEDITOR.tools.addFunction(function(){b.execCommand("toolbarCollapse")});b.on("destroy",function(){CKEDITOR.tools.removeFunction(C)});b.addCommand("toolbarCollapse",{readOnly:1,exec:function(a){var b=a.ui.space("toolbar_collapser"),c=b.getPrevious(),d=a.ui.space("contents"),e=c.getParent(),h=parseInt(d.$.style.height,10),g=e.$.offsetHeight,f=b.hasClass("cke_toolbox_collapser_min");f?(c.show(),b.removeClass("cke_toolbox_collapser_min"),b.setAttribute("title",
a.lang.toolbar.toolbarCollapse)):(c.hide(),b.addClass("cke_toolbox_collapser_min"),b.setAttribute("title",a.lang.toolbar.toolbarExpand));b.getFirst().setText(f?"▲":"◀");d.setStyle("height",h-(e.$.offsetHeight-g)+"px");a.fire("resize",{outerHeight:a.container.$.offsetHeight,contentsHeight:d.$.offsetHeight,outerWidth:a.container.$.offsetWidth})},modes:{wysiwyg:1,source:1}});b.setKeystroke(CKEDITOR.ALT+(CKEDITOR.env.ie||CKEDITOR.env.webkit?189:109),"toolbarCollapse");a.push('\x3ca title\x3d"'+(d?b.lang.toolbar.toolbarCollapse:
b.lang.toolbar.toolbarExpand)+'" id\x3d"'+b.ui.spaceId("toolbar_collapser")+'" tabIndex\x3d"-1" class\x3d"cke_toolbox_collapser');d||a.push(" cke_toolbox_collapser_min");a.push('" onclick\x3d"CKEDITOR.tools.callFunction('+C+')"\x3e','\x3cspan class\x3d"cke_arrow"\x3e\x26#9650;\x3c/span\x3e',"\x3c/a\x3e")}a.push("\x3c/span\x3e");c.data.html+=a.join("")}});b.on("destroy",function(){if(this.toolbox){var b,d=0,a,e,f;for(b=this.toolbox.toolbars;d<b.length;d++)for(e=b[d].items,a=0;a<e.length;a++)f=e[a],
f.clickFn&&CKEDITOR.tools.removeFunction(f.clickFn),f.keyDownFn&&CKEDITOR.tools.removeFunction(f.keyDownFn)}});b.on("uiReady",function(){var c=b.ui.space("toolbox");c&&b.focusManager.add(c,1)});b.addCommand("toolbarFocus",E);b.setKeystroke(CKEDITOR.ALT+121,"toolbarFocus");b.ui.add("-",CKEDITOR.UI_SEPARATOR,{});b.ui.addHandler(CKEDITOR.UI_SEPARATOR,{create:function(){return{render:function(b,d){d.push('\x3cspan class\x3d"cke_toolbar_separator" role\x3d"separator"\x3e\x3c/span\x3e');return{}}}}})}});
CKEDITOR.ui.prototype.addToolbarGroup=function(b,d,f){var c=v(this.editor),h=0===d,a={name:b};if(f){if(f=CKEDITOR.tools.search(c,function(a){return a.name==f})){!f.groups&&(f.groups=[]);if(d&&(d=CKEDITOR.tools.indexOf(f.groups,d),0<=d)){f.groups.splice(d+1,0,b);return}h?f.groups.splice(0,0,b):f.groups.push(b);return}d=null}d&&(d=CKEDITOR.tools.indexOf(c,function(a){return a.name==d}));h?c.splice(0,0,b):"number"==typeof d?c.splice(d+1,0,a):c.push(b)}})();CKEDITOR.UI_SEPARATOR="separator";
CKEDITOR.config.toolbarLocation="top";