/**
 * @license Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/* exported CKBUILDER_CONFIG */

var CKBUILDER_CONFIG = {
	skin: 'moono-lexicon',
	ignore: [
		'bender.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'_dev',
		'dev',
		'docs',
		'.DS_Store',
		'.editorconfig',
		'.gitignore',
		'.gitattributes',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests',
	],
	plugins: {
		a11yhelp: 1,
		basicstyles: 1,
		blockquote: 1,
		clipboard: 1,
		codemirror: 1,
		colorbutton: 1,
		contextmenu: 1,
		dialogadvtab: 1,
		enterkey: 1,
		font: 1,
		format: 1,
		horizontalrule: 1,
		htmlwriter: 1,
		image2: 1,
		imagespacingbox: 1,
		indentlist: 1,
		indentblock: 1,
		justify: 1,
		link: 1,
		list: 1,
		liststyle: 1,
		magicline: 1,
		pagebreak: 1,
		pastefromword: 1,
		pastetext: 1,
		pastetools: 1,
		removeformat: 1,
		resize: 1,
		tab: 1,
		table: 1,
		tabletools: 1,
		toolbar: 1,
		undo: 1,
		wysiwygarea: 1,
	},
};
