/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function n(a){if(!a||a.type!=CKEDITOR.NODE_ELEMENT||"form"!=a.getName())return[];for(var c=[],d=["style","className"],b=0;b<d.length;b++){var e=a.$.elements.namedItem(d[b]);e&&(e=new CKEDITOR.dom.element(e),c.push([e,e.nextSibling]),e.remove())}return c}function h(a,c){if(a&&a.type==CKEDITOR.NODE_ELEMENT&&"form"==a.getName()&&0<c.length)for(var d=c.length-1;0<=d;d--){var b=c[d][0],e=c[d][1];e?b.insertBefore(e):b.appendTo(a)}}function q(a,c){var d=n(a),b={},e=a.$;c||(b["class"]=e.className||
"",e.className="");b.inline=e.style.cssText||"";c||(e.style.cssText="position: static; overflow: visible");h(d);return b}function r(a,c){var d=n(a),b=a.$;"class"in c&&(b.className=c["class"]);"inline"in c&&(b.style.cssText=c.inline);h(d)}function t(a){if(!a.editable().isInline()){var c=CKEDITOR.instances,d;for(d in c){var b=c[d];"wysiwyg"!=b.mode||b.readOnly||(b=b.document.getBody(),b.setAttribute("contentEditable",!1),b.setAttribute("contentEditable",!0))}a.editable().hasFocus&&(a.toolbox.focus(),
a.focus())}}CKEDITOR.plugins.add("maximize",{lang:"af,ar,az,bg,bn,bs,ca,cs,cy,da,de,de-ch,el,en,en-au,en-ca,en-gb,eo,es,es-mx,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,oc,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn",icons:"maximize",hidpi:!0,init:function(a){function c(){var c=g.getViewPaneSize();a.resize(c.width,c.height,null,!0)}function d(){var c=a.getCommand("maximize");c.state===CKEDITOR.TRISTATE_ON&&c.exec()}if(a.elementMode!=
CKEDITOR.ELEMENT_MODE_INLINE){var b=a.lang,e=CKEDITOR.document,g=e.getWindow(),l,m,p,n=CKEDITOR.TRISTATE_OFF;a.addCommand("maximize",{modes:{wysiwyg:!CKEDITOR.env.iOS,source:!CKEDITOR.env.iOS},readOnly:1,editorFocus:!1,exec:function(){var b=a.container.getFirst(function(a){return a.type==CKEDITOR.NODE_ELEMENT&&a.hasClass("cke_inner")}),d=a.ui.space("contents");if("wysiwyg"==a.mode){var f=a.getSelection();l=f&&f.getRanges();m=g.getScrollPosition()}else{var k=a.editable().$;l=!CKEDITOR.env.ie&&[k.selectionStart,
k.selectionEnd];m=[k.scrollLeft,k.scrollTop]}if(this.state==CKEDITOR.TRISTATE_OFF){g.on("resize",c);p=g.getScrollPosition();for(f=a.container;f=f.getParent();)f.setCustomData("maximize_saved_styles",q(f)),f.setStyle("z-index",a.config.baseFloatZIndex-5);d.setCustomData("maximize_saved_styles",q(d,!0));b.setCustomData("maximize_saved_styles",q(b,!0));d={overflow:CKEDITOR.env.webkit?"":"hidden",width:0,height:0};e.getDocumentElement().setStyles(d);!CKEDITOR.env.gecko&&e.getDocumentElement().setStyle("position",
"fixed");CKEDITOR.env.gecko&&CKEDITOR.env.quirks||e.getBody().setStyles(d);CKEDITOR.env.ie?setTimeout(function(){g.$.scrollTo(0,0)},0):g.$.scrollTo(0,0);b.setStyle("position",CKEDITOR.env.gecko&&CKEDITOR.env.quirks?"fixed":"absolute");b.$.offsetLeft;b.setStyles({"z-index":a.config.baseFloatZIndex-5,left:"0px",top:"0px"});b.addClass("cke_maximized");c();d=b.getDocumentPosition();b.setStyles({left:-1*d.x+"px",top:-1*d.y+"px"});CKEDITOR.env.gecko&&t(a)}else if(this.state==CKEDITOR.TRISTATE_ON){g.removeListener("resize",
c);for(var f=[d,b],h=0;h<f.length;h++)r(f[h],f[h].getCustomData("maximize_saved_styles")),f[h].removeCustomData("maximize_saved_styles");for(f=a.container;f=f.getParent();)r(f,f.getCustomData("maximize_saved_styles")),f.removeCustomData("maximize_saved_styles");CKEDITOR.env.ie?setTimeout(function(){g.$.scrollTo(p.x,p.y)},0):g.$.scrollTo(p.x,p.y);b.removeClass("cke_maximized");CKEDITOR.env.webkit&&(b.setStyle("display","inline"),setTimeout(function(){b.setStyle("display","block")},0));a.fire("resize",
{outerHeight:a.container.$.offsetHeight,contentsHeight:d.$.offsetHeight,outerWidth:a.container.$.offsetWidth})}this.toggleState();"wysiwyg"==a.mode?l?(CKEDITOR.env.gecko&&t(a),a.getSelection().selectRanges(l),(k=a.getSelection().getStartElement())&&k.scrollIntoView(!0)):g.$.scrollTo(m.x,m.y):(l&&(k.selectionStart=l[0],k.selectionEnd=l[1]),k.scrollLeft=m[0],k.scrollTop=m[1]);l=m=null;n=this.state;a.fire("maximize",this.state)},canUndo:!1});a.ui.addButton&&a.ui.addButton("Maximize",{isToggle:!0,label:b.maximize.maximize,
command:"maximize",toolbar:"tools,10"});a.on("mode",function(){var b=a.getCommand("maximize");b.setState(b.state==CKEDITOR.TRISTATE_DISABLED?CKEDITOR.TRISTATE_DISABLED:n)},null,null,100);if(a.config.maximize_historyIntegration){var h=a.config.maximize_historyIntegration===CKEDITOR.HISTORY_NATIVE?"popstate":"hashchange";g.on(h,d);a.on("destroy",function(){g.removeListener(h,d)})}}}});CKEDITOR.config.maximize_historyIntegration=CKEDITOR.HISTORY_NATIVE})();